version: "3"

services:
  app:
    build:
      docker/php
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: lar_db
      MYSQL_PASSWORD: lar_pass


